### ISSUE TITLE
Design contribution

### ISSUE THREAD

**Issue by masudr4n4** [ekaputra07/quick-sms#6]
I am seeing that your app icon is so normal that does not refer to the app.i am a designer want to make a logo for this app if you have any idea or requirements then let me know.Its free for open source projects.
thank you

**Comment by ekaputra07** [comment]
Hi @maaudrana, thanks for your kind offer.

Actually I haven't any specific requirements, but since this app is already live on Google play so I would stick with the current blue theme for now. So if you could make a design around that colour that would be good.

If I'm happy with the result, I'll add you as the contributor and also credit you on the app.

Thank you

**Comment by masudr4n4** [comment]
i make a 3 type logo which logo you like please comment. if you need anything change please commend.

![sms-01](https://user-images.githubusercontent.com/34313493/42732368-106c9ae8-8842-11e8-8e72-0ab2d3258990.jpg)

**Comment by ekaputra07** [comment]
Hi @maaudrana nice work,
I think I like the first one but **_without extra shadow_** on the left.

And below is the original icon design, could you please use the same background color (and white text)? because the app it self also using this same color.

Thanks

![512](https://user-images.githubusercontent.com/1094221/42741882-b3c0a378-88e8-11e8-8f12-a633df7c03ac.png)

**Comment by masudr4n4** [comment]
![sms 2-01](https://user-images.githubusercontent.com/34313493/42772456-51978270-894c-11e8-9a1d-0257245a8eab.jpg)

**Comment by ekaputra07** [comment]
@maaudrana Nice!

I will use this. Btw how you will integrate this icon to the app?
will you create a PR or you'll attach them here?

**Comment by masudr4n4** [comment]
Yes,i will create a PR.

**Comment by ekaputra07** [comment]
Thanks @maaudrana your PR has been merged. 👍

**Comment by masudr4n4** [comment]
You are welcome.feeel free to  any design for open source project in future
I am open source contributor.

**Comment by masudr4n4** [comment]
@ekaputra07
all the editable file the logo uploaded to  
[drive](https://drive.google.com/open?id=1TcwXA1Wlbcy8uKi-ixv1c6z5Um6uPrWt)
you can use it freely as your wish.
